# Generated by Django 3.1 on 2020-12-05 06:52

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, default=posts.models.get_default_header_image, null=True, upload_to='images/post_headers/'),
        ),
    ]
